// Code generated by LVGL UI Generator

#include "lvgl.h"

// Forward declaration for any registered C pointers you might have from your application.
// Example: extern const lv_font_t my_custom_font;
void create_ui(lv_obj_t* parent) {
    {
        lv_style_t* s_test_style_for_nulls = (lv_style_t*)malloc(sizeof(lv_style_t));
        if (s_test_style_for_nulls != NULL) {
            memset(s_test_style_for_nulls, 0, sizeof(lv_style_t));
            lv_style_init(s_test_style_for_nulls);
        } else {
            fprintf(stderr, "Error: Failed to malloc for object %s of type %s\n", "s_test_style_for_nulls", "lv_style_t");
        }
    }
    {
        lv_obj_t* l_test_label_for_nulls = lv_label_create(parent);
        lv_label_set_text(l_test_label_for_nulls, "Initial Text");
    }
    {
        lv_obj_t* dummy_with_1 = lv_obj_create(parent);
    }
    {
        lv_obj_t* dummy_with_2 = lv_obj_create(parent);
        lv_style_t* with_target_0 = &s_test_style_for_nulls;
        lv_style_set_bg_color(with_target_0, lv_color_hex(0));
        lv_style_set_border_width(with_target_0, 0);
        lv_style_set_outline_opa(with_target_0, 0);
        lv_style_set_shadow_color(with_target_0, lv_color_hex(0));
    }
}
