/*
 * AUTO-GENERATED by generate_dynamic_lvgl_dispatch.py.
 * DO NOT EDIT MANUALLY.
 */
#ifndef DYNAMIC_LVGL_H
#define DYNAMIC_LVGL_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include <stdio.h>
#include <stdlib.h>

#include "api_spec.h"
#include "registry.h" // Include for Registry type

typedef struct IRNode IRNode;
struct ApiSpec; /* Forward declaration for ApiSpec pointer usage */
struct Registry; // Forward declaration for Registry pointer usage

// --- Object Registry (using the new registry.h system) ---
// These are now wrappers or direct calls to the main registry.
// Initialization and deinitialization are handled externally via registry_create/free.
void obj_registry_add(struct Registry* reg, const char* id, void* obj);
char* obj_registry_add_str(struct Registry* reg, const char* s);
void* obj_registry_get(struct Registry* reg, const char* id);
// obj_registry_init and obj_registry_deinit are effectively replaced by
// registry_create() and registry_free() called by the main application.


// --- Dynamic Dispatcher ---
// Calls an LVGL function by name, with arguments provided as an array of IR nodes.
// The renderer is responsible for resolving complex IR expressions (like context vars)
// into simpler, self-contained IR nodes (literals, registry refs) before calling.
// Added ApiSpec* spec and Registry* reg arguments.
lv_obj_t* dynamic_lvgl_call_ir(const char* func_name, void* target_obj, IRNode** ir_args, int arg_count, struct ApiSpec* spec, struct Registry* reg);

#ifdef __cplusplus
}
#endif

#endif // DYNAMIC_LVGL_H
