/*
 * AUTO-GENERATED by generate_dynamic_lvgl_dispatch.py.
 * Consolidation: aggressive
 * DO NOT EDIT MANUALLY.
 */
#ifndef DYNAMIC_LVGL_H
#define DYNAMIC_LVGL_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>

#include "lvgl.h"
#include "cJSON.h"

#include "utils.h"

#if defined(ENABLE_IR_INPUTS)
typedef struct IRNode IRNode;
#endif

void obj_registry_init(void);
void obj_registry_add(const char* id, void* obj);
void* obj_registry_get(const char* id);
void obj_registry_deinit(void);

#if defined(ENABLE_CJSON_INPUTS)

lv_obj_t* dynamic_lvgl_call_json(const char* func_name, void* target_obj, cJSON* args);
int unmarshal_value(cJSON* value, const char* expected_enum_type_for_arg);
#endif // ENABLE_CJSON_INPUTS

#if defined(ENABLE_IR_INPUTS)

lv_obj_t* dynamic_lvgl_call_ir(const char* func_name, void* target_obj, IRNode** ir_args, int arg_count);
#endif // ENABLE_IR_INPUTS


#ifdef __cplusplus
}
#endif

#endif // DYNAMIC_LVGL_H
