#ifndef LVGL_UI_H
#define LVGL_UI_H

#include "lvgl.h"
#include "data_binding.h"
#include "obj_registry.h"
#include "deferred_loader.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initializes the runtime services required by the generated UI.
 * Call this once before creating the UI (e.g., before calling create_ui).
 */
void lvgl_ui_init(void);

/**
 * @brief Deinitializes the runtime services, freeing any allocated memory.
 */
void lvgl_ui_deinit(void);

/**
 * @brief A placeholder declaration for the UI creation function.
 * This function will be defined in the C file generated by the lvgl_ui_generator.
 *
 * @param parent The parent lv_obj_t* onto which the UI should be created.
 */
extern void create_ui(lv_obj_t* parent);

/**
 * @brief Destroys the UI rooted at *root_ptr and reclaims all file-scope
 * allocations made by create_ui (e.g. hoisted lv_style_t* objects).
 *
 * If root_ptr is NULL or *root_ptr is NULL the call is a no-op and LVGL is
 * assumed to clean up via the parent chain.  On return, *root_ptr is set to
 * NULL.
 *
 * @param root_ptr Pointer to the root lv_obj_t* passed to create_ui.
 */
extern void destroy_ui(lv_obj_t** root_ptr);

#ifdef __cplusplus
}
#endif

#endif // LVGL_UI_H
