#ifndef LVGL_UI_H
#define LVGL_UI_H

#include "lvgl.h"
#include "data_binding.h"
#include "obj_registry.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initializes the runtime services required by the generated UI.
 * Call this once before creating the UI (e.g., before calling create_ui).
 */
void lvgl_ui_init(void);

/**
 * @brief Deinitializes the runtime services, freeing any allocated memory.
 */
void lvgl_ui_deinit(void);

/**
 * @brief A placeholder declaration for the UI creation function.
 * This function will be defined in the C file generated by the lvgl_ui_generator.
 *
 * @param parent The parent lv_obj_t* onto which the UI should be created.
 */
extern void create_ui(lv_obj_t* parent);

#ifdef __cplusplus
}
#endif

#endif // LVGL_UI_H
