#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <cJSON.h> // Changed from <cJSON/cJSON.h>

#include "utils.h"    // For read_file
#include "api_spec.h" // For ApiSpec & functions
#include "registry.h" // For Registry (though mainly used by generator)
#include "generator.h"  // For generate_ir_from_ui_spec
#include "ir.h"       // For IRStmtBlock, IRNode, ir_free
#include "codegen.h"  // For codegen_generate_c

int main(int argc, char* argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <api_spec.json> <ui_spec.json>\n", argv[0]);
        return 1;
    }

    // --- Load Files ---
    char* api_spec_str = read_file(argv[1]);
    if (!api_spec_str) return 1;
    char* ui_spec_str = read_file(argv[2]);
    if (!ui_spec_str) { free(api_spec_str); return 1; }

    // --- Parse JSON ---
    cJSON* api_json = cJSON_Parse(api_spec_str);
    if (!api_json) {
        fprintf(stderr, "Error parsing API SPEC JSON: %s\n", cJSON_GetErrorPtr());
        goto cleanup_str;
    }
    cJSON* ui_json = cJSON_Parse(ui_spec_str);
    if (!ui_json) {
        fprintf(stderr, "Error parsing UI SPEC JSON: %s\n", cJSON_GetErrorPtr());
        goto cleanup_json; // api_json needs cleanup
    }

    // --- Process ---
    // 1. Parse the API spec into an internal, efficient format
    ApiSpec* api_spec = api_spec_parse(api_json); // api_spec.c should provide this
    if (!api_spec) {
        fprintf(stderr, "Error: Failed to parse API spec.\n");
        goto cleanup_json; // ui_json and api_json need cleanup
    }

    // 2. Generate the Intermediate Representation (IR) from the UI spec
    // The generator will create and use its own registry internally.
    IRStmtBlock* ir = generate_ir_from_ui_spec(ui_json, api_spec); // generator.c provides this
    if (!ir) {
        fprintf(stderr, "Error: Failed to generate IR from UI spec.\n");
        api_spec_free(api_spec); // Free api_spec before goto
        goto cleanup_json; // ui_json and api_json need cleanup
    }

    // 3. Generate C code from the IR
    printf("// Code generated by LVGL UI Generator\n\n");
    printf("#include \"lvgl.h\"\n\n");
    printf("// Forward declaration for any registered C pointers you might have from your application.\n");
    printf("// Example: extern const lv_font_t my_custom_font;\n");
    // Example of how a global parent might be declared if not passed directly
    // printf("// extern lv_obj_t *%s;\n\n", "parent_scr");

    // Output the create_ui function signature
    printf("void create_ui(lv_obj_t* parent) {\n"); // "parent" is the typical name for the top-level parent in LVGL examples

    // Generate the C code for the UI elements based on the IR
    codegen_generate_c(ir, "parent"); // Pass "parent" as the top-level parent variable name

    printf("}\n");


    // --- Cleanup ---
    ir_free((IRNode*)ir);         // Free the entire IR tree
    api_spec_free(api_spec);      // Free the parsed API spec
cleanup_json:
    cJSON_Delete(ui_json);        // Free UI spec JSON object
    cJSON_Delete(api_json);       // Free API spec JSON object
cleanup_str:
    free(ui_spec_str);            // Free UI spec string
    free(api_spec_str);           // Free API spec string

    return 0;
}
