#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h> // For strcmp
#include <cJSON.h>

#include "utils.h"    // For read_file
#include "api_spec.h" // For ApiSpec & functions
#include "registry.h" // For Registry (though mainly used by generator)
#include "generator.h"  // For generate_ir_from_ui_spec
#include "ir.h"       // For IRStmtBlock, IRNode, ir_free
#include "codegen.h"  // For codegen_generate_c
#include "viewer/sdl_viewer.h" // For SDL viewer functions
#include "lvgl_ui_renderer.h" // For LVGL UI rendering functions

typedef enum {
    CODEGEN_MODE_C_CODE,
    CODEGEN_MODE_LVGL_UI,
    CODEGEN_MODE_C_CODE_AND_LVGL_UI
} CodegenMode;

void print_usage(const char* prog_name) {
    fprintf(stderr, "Usage: %s [--codegen <mode>] <api_spec.json> <ui_spec.json>\n", prog_name);
    fprintf(stderr, "Modes: c_code, lvgl_ui, c_code_and_lvgl_ui (default)\n");
}

int main(int argc, char* argv[]) {
    CodegenMode mode = CODEGEN_MODE_C_CODE_AND_LVGL_UI; // Default mode
    char* api_spec_path = NULL;
    char* ui_spec_path = NULL;
    int i;

    // Parse arguments
    for (i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "--codegen") == 0) {
            if (i + 1 < argc) {
                i++; // Consume mode value
                if (strcmp(argv[i], "c_code") == 0) {
                    mode = CODEGEN_MODE_C_CODE;
                } else if (strcmp(argv[i], "lvgl_ui") == 0) {
                    mode = CODEGEN_MODE_LVGL_UI;
                } else if (strcmp(argv[i], "c_code_and_lvgl_ui") == 0) {
                    mode = CODEGEN_MODE_C_CODE_AND_LVGL_UI;
                } else {
                    fprintf(stderr, "Error: Unknown codegen mode '%s'\n", argv[i]);
                    print_usage(argv[0]);
                    return 1;
                }
            } else {
                fprintf(stderr, "Error: --codegen flag requires a mode argument.\n");
                print_usage(argv[0]);
                return 1;
            }
        } else if (!api_spec_path) {
            api_spec_path = argv[i];
        } else if (!ui_spec_path) {
            ui_spec_path = argv[i];
        } else {
            fprintf(stderr, "Error: Too many positional arguments.\n");
            print_usage(argv[0]);
            return 1;
        }
    }

    if (!api_spec_path || !ui_spec_path) {
        fprintf(stderr, "Error: Missing api_spec.json or ui_spec.json path.\n");
        print_usage(argv[0]);
        return 1;
    }

    // --- Load Files ---
    char* api_spec_str = read_file(api_spec_path);
    if (!api_spec_str) return 1;
    char* ui_spec_str = read_file(ui_spec_path);
    if (!ui_spec_str) { free(api_spec_str); return 1; }

    // --- Parse JSON ---
    cJSON* api_json = cJSON_Parse(api_spec_str);
    if (!api_json) {
        fprintf(stderr, "Error parsing API SPEC JSON: %s\n", cJSON_GetErrorPtr());
        goto cleanup_str;
    }
    cJSON* ui_json = cJSON_Parse(ui_spec_str);
    if (!ui_json) {
        fprintf(stderr, "Error parsing UI SPEC JSON: %s\n", cJSON_GetErrorPtr());
        goto cleanup_json; // api_json needs cleanup
    }

    // --- Process ---
    // 1. Parse the API spec into an internal, efficient format
    ApiSpec* api_spec = api_spec_parse(api_json); // api_spec.c should provide this
    if (!api_spec) {
        fprintf(stderr, "Error: Failed to parse API spec.\n");
        goto cleanup_json; // ui_json and api_json need cleanup
    }

    // 2. Generate the Intermediate Representation (IR) from the UI spec
    // The generator will create and use its own registry internally.
    IRStmtBlock* ir = generate_ir_from_ui_spec(ui_json, api_spec); // generator.c provides this
    if (!ir) {
        fprintf(stderr, "Error: Failed to generate IR from UI spec.\n");
        api_spec_free(api_spec); // Free api_spec before goto
        goto cleanup_json; // ui_json and api_json need cleanup
    }

    // 3. Perform actions based on codegen mode
    if (mode == CODEGEN_MODE_C_CODE || mode == CODEGEN_MODE_C_CODE_AND_LVGL_UI) {
        printf("// Code generated by LVGL UI Generator\n\n");
        printf("#include \"lvgl.h\"\n\n");
        printf("// Forward declaration for any registered C pointers you might have from your application.\n");
        printf("// Example: extern const lv_font_t my_custom_font;\n");
        // Example of how a global parent might be declared if not passed directly
        // printf("// extern lv_obj_t *%s;\n\n", "parent_scr");

        // Output the create_ui function signature
        printf("void create_ui(lv_obj_t* parent) {\n"); // "parent" is the typical name for the top-level parent in LVGL examples

        // Generate the C code for the UI elements based on the IR
        codegen_generate_c(ir, "parent"); // Pass "parent" as the top-level parent variable name

        printf("}\n");
    }

    if (mode == CODEGEN_MODE_LVGL_UI || mode == CODEGEN_MODE_C_CODE_AND_LVGL_UI) {
        if (sdl_viewer_init() != 0) {
            fprintf(stderr, "Error: Failed to initialize SDL viewer.\n");
            ir_free((IRNode*)ir);
            api_spec_free(api_spec);
            cJSON_Delete(ui_json);
            cJSON_Delete(api_json);
            free(ui_spec_str);
            free(api_spec_str);
            return 1;
        }

        lv_obj_t* main_screen = sdl_viewer_create_main_screen();
        if (!main_screen) {
            fprintf(stderr, "Error: Failed to create main LVGL screen.\n");
            sdl_viewer_deinit(); // Clean up SDL parts that were initialized
            ir_free((IRNode*)ir);
            api_spec_free(api_spec);
            cJSON_Delete(ui_json);
            cJSON_Delete(api_json);
            free(ui_spec_str);
            free(api_spec_str);
            return 1;
        }

        // Pass the api_spec to the renderer
        render_lvgl_ui_from_ir(ir, main_screen, api_spec);

        sdl_viewer_loop(); // This is an infinite loop

        // sdl_viewer_deinit() won't be reached if sdl_viewer_loop is infinite.
        // This is typical for UI applications; cleanup happens on process exit.
        // If sdl_viewer_loop could terminate, deinit would go here.
        // sdl_viewer_deinit();
    }

    // --- Cleanup ---
    ir_free((IRNode*)ir);         // Free the entire IR tree
    api_spec_free(api_spec);      // Free the parsed API spec
cleanup_json:
    cJSON_Delete(ui_json);        // Free UI spec JSON object
    cJSON_Delete(api_json);       // Free API spec JSON object
cleanup_str:
    free(ui_spec_str);            // Free UI spec string
    free(api_spec_str);           // Free API spec string

    // If only LVGL UI was shown, sdl_viewer_deinit might be called here if loop wasn't infinite
    // However, given the current structure, it's complex to place it correctly for all modes
    // without restructuring the main loop or signal handling.
    // For now, relying on OS to clean up SDL resources on program exit after infinite loop.
    if (mode == CODEGEN_MODE_LVGL_UI || mode == CODEGEN_MODE_C_CODE_AND_LVGL_UI) {
         // If sdl_viewer_loop was not infinite, this would be the place for sdl_viewer_deinit()
         // sdl_viewer_deinit();
    }


    return 0;
}
