#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h> // Required for strlen
#include <cJSON.h>

#include "utils.h"    // For read_file
#include "api_spec.h" // For ApiSpec & functions
#include "registry.h"
#include "generator.h"  // For generate_ir_from_ui_spec
#include "ir.h"       // For IRStmtBlock, IRNode, ir_free
#include "codegen.h"  // For codegen_generate_c

int main(int argc, char* argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <api_spec.json> <ui_spec.json>\n", argv[0]);
        return 1;
    }

    // --- Load Files ---
    char* buffer_api_spec_file = read_file(argv[1]);
    if (!buffer_api_spec_file) {
        // read_file already prints an error
        return 1;
    }
    // DEBUG: Print content of api_spec.json
    fprintf(stderr, "DEBUG main: api_spec.json content loaded. First 80 chars: %.*s\n", 80, buffer_api_spec_file);
    fprintf(stderr, "DEBUG main: api_spec.json content loaded, length: %zu\n", strlen(buffer_api_spec_file));
    fflush(stderr);

    char* buffer_ui_spec_file = read_file(argv[2]);
    if (!buffer_ui_spec_file) {
        free(buffer_api_spec_file);
        return 1;
    }

    // --- Parse JSON ---
    cJSON* api_spec_json_root = cJSON_Parse(buffer_api_spec_file);
    fprintf(stderr, "DEBUG main: cJSON_Parse for api_spec.json returned: %p\n", (void*)api_spec_json_root);
    fflush(stderr);

    if (api_spec_json_root == NULL) {
        const char *error_ptr = cJSON_GetErrorPtr();
        fprintf(stderr, "FATAL main: cJSON_Parse failed for api_spec.json. ");
        if (error_ptr != NULL) {
            fprintf(stderr, "Error before: [%s]\n", error_ptr);
        } else {
            fprintf(stderr, "No specific error pointer from cJSON.\n");
        }
        fflush(stderr);
        // Not exiting here to match original behavior, but subsequent steps will likely fail.
        // If spec remains NULL, other errors will occur.
    }

    cJSON* ui_json_root = cJSON_Parse(buffer_ui_spec_file);
    if (!ui_json_root) {
        fprintf(stderr, "Error parsing UI SPEC JSON (%s): %s\n", argv[2], cJSON_GetErrorPtr());
        goto cleanup_api_spec_json_obj; // api_spec_json_root needs cleanup if not NULL
    }

    // --- Process ---
    fprintf(stderr, "DEBUG main: Calling api_spec_parse with api_spec_json_root: %p\n", (void*)api_spec_json_root);
    fflush(stderr);
    ApiSpec* spec = api_spec_parse(api_spec_json_root);
    fprintf(stderr, "DEBUG main: api_spec_parse returned ApiSpec pointer: %p\n", (void*)spec);
    fflush(stderr);

    if (!spec) {
        fprintf(stderr, "Error: Failed to parse API spec (api_spec_parse returned NULL).\n");
        // No need to call api_spec_free(spec) as spec is NULL
        goto cleanup_all_json;
    }

    IRStmtBlock* ir_root = generate_ir_from_ui_spec(ui_json_root, spec);
    if (!ir_root) {
        fprintf(stderr, "Error: Failed to generate IR from UI spec.\n");
        api_spec_free(spec);
        goto cleanup_all_json;
    }

    // --- Generate C code ---
    printf("// Code generated by LVGL UI Generator\n\n");
    printf("#include \"lvgl.h\"\n\n");
    printf("// Forward declaration for any registered C pointers you might have from your application.\n");
    printf("// Example: extern const lv_font_t my_custom_font;\n");

    printf("void create_ui(lv_obj_t* parent) {\n");
    codegen_generate_c(ir_root, "parent");
    printf("}\n");

    // --- Cleanup ---
    ir_free((IRNode*)ir_root);
    api_spec_free(spec);
cleanup_all_json:
    cJSON_Delete(ui_json_root);
cleanup_api_spec_json_obj:
    if(api_spec_json_root) cJSON_Delete(api_spec_json_root); // Free API spec JSON object if parsed
// cleanup_str: // labels must be followed by statements
    free(buffer_ui_spec_file);
    free(buffer_api_spec_file);

    return 0;
}
