// Code generated by LVGL UI Generator

#include "lvgl.h"

// Forward declaration for any registered C pointers you might have from your application.
// Example: extern const lv_font_t my_custom_font;
void create_ui(lv_obj_t* parent) {
    {
        // Info: Type 'derived_widget' (var test_obj) has no specific create/init. Creating as lv_obj_t and applying properties.
        lv_obj_t* test_obj = lv_obj_create(parent);
        {
            // Info: Type 'derived_widget' (var my_derived) has no specific create/init. Creating as lv_obj_t and applying properties.
            lv_obj_t* my_derived = lv_obj_create(test_obj);
            lv_base_set_base_prop(my_derived, 10);
            lv_derived_set_derived_prop(my_derived, true);
            base_method(my_derived, 20);
            derived_method(my_derived, 30, 40);
            lv_obj_specific_method(my_derived, 50);
            global_func_direct(my_derived, 60);
            lv_obj_global_func_prefixed(my_derived, "hello");
            other_method(my_derived, "world");
        }
    }
}
